---
- name: "copy compiled files"
  become: yes
  synchronize:
    src: ../../backend/dist
    dest: /home/ubuntu/uda_backend
    recursive: true

- name: "copy node_modules"
  become: yes
  synchronize:
    src: ../../backend/node_modules
    dest: /home/ubuntu/uda_backend
    recursive: true

- name: "start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/uda_backend/dist